import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Navbar } from "~/components/navbar";
import { ThemeProvider } from "~/components/theme-provider";
import { Footer } from "~/components/footer";
import { FadeIn } from "~/components/fadein";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={`${GeistSans.variable}`}>
            <body>
                <div className="max-w-[824px] mx-auto px-8 sm:px-6">
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem={true}
                        disableTransitionOnChange={true}
                    >
                        <FadeIn>
                            <Navbar />
                            {children}
                            <Footer />
                        </FadeIn>
                    </ThemeProvider>
                </div>
            </body>
        </html >
    );
}
